import datetime
t=datetime.time(4,20,1)
print(t.hour)
print(t.minute)
print(t.second)
print(datetime.time.min)
today=datetime.date.today()
print(today)
print(today.ctime)
today=datetime.datetime(2017,1,2,10)
print(today.ctime())
print(today.year)
d1=datetime.date(2019,8,17)
d2=datetime.date(2016,8,10)
print(d1-d2)
srtDate=d1.strftime('%Y-%m-%d')
print(srtDate)
print(type(srtDate))